### ISSUE TITLE
项目挂了，楼主可以再维护一下吗

### ISSUE THREAD

**Issue by GMYXDS** [lzr936332553/yiban_Automation_tool#12]
### Start
验证码识别错误
###--使用了验证码，验证码是: 1
验证码识别错误
###--使用了验证码，验证码是: 1
###--模拟登陆成功
###--签到状态：操作成功
yiban_Automation_tool:如果我报错了，请在GitHub上联系原作者： HTTP Error 514: 
yiban_Automation_tool:如果我报错了，请在GitHub上联系原作者： HTTP Error 514: 
yiban_Automation_tool:如果我报错了，请在GitHub上联系原作者： HTTP Error 514: 
yiban_Automation_tool:如果我报错了，请在GitHub上联系原作者： HTTP Error 514:

**Comment by SadTomlzr** [comment]
如果使用的是release版本。可以在config文件里取消yiyan功能。
> "isYiYan":"False",
即可

**Comment by rick-lzr** [comment]
如果使用的是release版本。可以在config文件里取消yiyan功能。
> "isYiYan":"False",

即可

如果是代码版需要在egpa文件里修改yiyan随机话的生成方式。
方法：注释yiyan方法里所有方法。return一个固定的字符串即可"xxxxxx"

关于维护的话，最近一个月大概率也不会维护了。2021年1.1后应该就会维护。

**Comment by rick-lzr** [comment]
新版本可以查看release。V1.4
